### ISSUE TITLE
Could not find file at path:

### ISSUE THREAD

**Issue by Kelthic** [Boxofbiscuits97/HD2SDK-CommunityEdition#9]
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 3993, in execute
    Global_TocManager.Save(int(EntryID), MaterialID)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1230, in Save
    Entry.Save()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 924, in Save
    data = callback(self, self.FileID, self.TocData, self.GpuData, self.StreamData, self.LoadedData)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1425, in SaveStingrayMaterial
    raise Exception(f"Could not find file at path: {path}")
Exception: Could not find file at path: C:\Users\user\AppData\Local\Temp\13501168202567337349.png
```

I trying to save Basic+ material to create three textures for replacing. I getting this error.

How to fix that if Blender have no any restrictions?

**Comment by Kelthic** [comment]
## Okay i fixed that:

1) Open "Run" using "Win+R"
2) Type "%appdata%"
3) Click Enter
4) Find "Blender Foundation" and open it
5) Find 4.0 folder and delete that using Right Button Mouse or using Shift+Delete (force delete)
6) Done. Relaunch Blender 4.0 and this is fixed

## WARNING
Be aware, this method  fully clean up the Blender 4.0!

**Comment by Kelthic** [comment]
Again that error and my method aint working now.
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 4160, in execute
    Global_TocManager.Save(int(EntryID), MaterialID)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1290, in Save
    Entry.Save()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 984, in Save
    data = callback(self, self.FileID, self.TocData, self.GpuData, self.StreamData, self.LoadedData)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1523, in SaveStingrayMaterial
    raise Exception(f"Could not find file at path: {path}")
Exception: Could not find file at path: C:\Users\user\AppData\Local\Temp\16289846176447101459.png
```

Any idea how to fix that?

**Comment by Boxofbiscuits97** [comment]
This is a bug I've been trying to squash for a while. I believe it has something to do with the texture conversion when saving a material. You should be able to select textures for each texture slot instead of leaving it as what the material has by default and it should fix the problem.

**Comment by Boxofbiscuits97** [comment]
Fixed in [v2.7.1](https://github.com/Boxofbiscuits97/HD2SDK-CommunityEdition/releases/tag/v2.7.1)

**Comment by catnapperthebig** [comment]
```Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 4401, in execute
    Global_TocManager.Save(int(EntryID), MaterialID)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1334, in Save
    Entry.Save()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1028, in Save
    data = callback(self, self.FileID, self.TocData, self.GpuData, self.StreamData, self.LoadedData)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1567, in SaveStingrayMaterial
    raise Exception(f"Could not find file at path: {path}")
Exception: Could not find file at path: C:\Users\user\AppData\Local\Temp\16289846176447101459.png
```
The problem is still present. Reinstalling the SDK did not help, the problem was fixed by replacing every non-visible image texture with a blank black square image but that's not ideal.
Blender 4.0.2, HD2SDK version 2.7.5

**Comment by Boxofbiscuits97** [comment]
Should properly be fixed now

**Comment by Kelthic** [comment]
Greetings againt. 2.8.5:
```python
Python: Traceback (most recent call last):
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 4676, in execute
    Global_TocManager.Save(int(EntryID), MaterialID)
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1378, in Save
    Entry.Save()
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1069, in Save
    data = callback(self, self.FileID, self.TocData, self.GpuData, self.StreamData, self.LoadedData)
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1611, in SaveStingrayMaterial
    raise Exception(f"Could not find file at path: {path}")
Exception: Could not find file at path: C:\Users\Kelthic\AppData\Local\Temp\11580353517303692747.png
```
Is this have that error again in new release.

**Comment by Boxofbiscuits97** [comment]
The problem should be solved as of v2.9.0.

**Comment by Kelthic** [comment]
```Python
Python: Traceback (most recent call last):
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 4756, in execute
    Global_TocManager.Save(int(EntryID), MaterialID)
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1378, in Save
    Entry.Save()
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1019, in Save
    data = callback(self, self.FileID, self.TocData, self.GpuData, self.StreamData, self.LoadedData)
  File "C:\Users\Kelthic\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\HD2SDK-CommunityEdition\__init__.py", line 1611, in SaveStingrayMaterial
    raise Exception(f"Could not find file at path: {path}")
Exception: Could not find file at path: C:\Users\Kelthic\AppData\Local\Temp\16289846176447101459.png

```

Nope, that's not solved. I don't understand what's wrong with SDK.

**Comment by Boxofbiscuits97** [comment]
This issue is still most definitely persisting so let me just write some notes here to track what's going on.

- This is possibly due to texture IDs being shuffled at material save time. So it physically just cannot find the new textures it's trying to save since the name of the file ID has changed according to the SDK even though the original images with the old IDs still exist
- It might be just a good idea to ignore the textures if they are not changed and just not reshuffle the IDs or possibly even just completely omit the textures from the patch files as that causes some bloat in the patch since we're just including the unmodified textures over and over again with any mod using the Advanced material template

**Comment by Boxofbiscuits97** [comment]
> The problem is i cannot create materials. This error disable possibility to create mods, cos I could put mesh and save it, but not materials which I can't create.

Yes I'm aware that this halts your ability to create materials. You *should* just be able to put blank textures in all of the other textures slots for the Advanced Material as a temporary workaround. It's just the default textures from the game are not being found by the SDK but you should be able to continue modding if you put in blank textures everywhere else.
